// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5njs904MzGeffhGx3zJ8EBxqKUiQQBQI',
    appId: '1:37129700910:web:1e42649f85e2fedcb8c1bf',
    messagingSenderId: '37129700910',
    projectId: 'chatflutter-102a6',
    authDomain: 'chatflutter-102a6.firebaseapp.com',
    databaseURL: 'https://chatflutter-102a6-default-rtdb.firebaseio.com',
    storageBucket: 'chatflutter-102a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2Bvpf7Y440W8oDTkPnTv7gqONJhVq-Y',
    appId: '1:827788806706:android:a792ed6f99925081114a2b',
    messagingSenderId: '827788806706',
    projectId: 'chatflutter-e56a7',
    storageBucket: 'chatflutter-e56a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIqzVRYq-NApPdayy_Ps-FAN9XOSX6Yro',
    appId: '1:827788806706:ios:3140394d51806471114a2b',
    messagingSenderId: '827788806706',
    projectId: 'chatflutter-e56a7',
    storageBucket: 'chatflutter-e56a7.firebasestorage.app',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQthqcTJbb3BgrgASFEKSMxJr2uKJYnFA',
    appId: '1:37129700910:ios:39467b0d2ff06d51b8c1bf',
    messagingSenderId: '37129700910',
    projectId: 'chatflutter-102a6',
    databaseURL: 'https://chatflutter-102a6-default-rtdb.firebaseio.com',
    storageBucket: 'chatflutter-102a6.firebasestorage.app',
    androidClientId: '37129700910-3jn9a9ipm5b2khtcavfa3an57v6m7e7v.apps.googleusercontent.com',
    iosClientId: '37129700910-9f7l57tle2di012gqg5rtremblf97fbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5njs904MzGeffhGx3zJ8EBxqKUiQQBQI',
    appId: '1:37129700910:web:07089baba302583eb8c1bf',
    messagingSenderId: '37129700910',
    projectId: 'chatflutter-102a6',
    authDomain: 'chatflutter-102a6.firebaseapp.com',
    databaseURL: 'https://chatflutter-102a6-default-rtdb.firebaseio.com',
    storageBucket: 'chatflutter-102a6.firebasestorage.app',
  );
}